(global-set-key (kbd "C-x C-z") nil)
(global-set-key (kbd "C-z") nil)
(global-set-key (kbd "C-c C-g") 'magit-status)
(global-set-key (kbd "C-c C-r") 'replace-string)
(add-hook 'nxml-mode-hook (lambda ()
                            (local-set-key (kbd "C-c p")
                                           'nxml-where)
                            (local-set-key (kbd "C-<return>")
                                           'xml-return)))
